AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample Lambda that uses DynamoDB

Globals:
  Function:
    Timeout: 60
  Api:
    Cors: 
      AllowMethods: "'OPTIONS,POST'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'" 

Resources:
  COVIDSafeLocationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "locationId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "locationId"
          KeyType: "HASH"
      TableName: "aa-covidsafe-locations"
      BillingMode: PAY_PER_REQUEST
  COVIDSafeRegistrationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "locationId"
          AttributeType: "S"
        - AttributeName: "visitId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "locationId"
          KeyType: "HASH"
        - AttributeName: "visitId"
          KeyType: "RANGE"
      TableName: "aa-covidsafe-registrations"
      BillingMode: PAY_PER_REQUEST
  COVIDSafeFormRenderFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: COVIDSafeFormRenderFunctionRole
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        - PolicyName: AccessToDynamoDbLocationsTable
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: !GetAtt
                  - COVIDSafeLocationsTable
                  - Arn
      Path: /
  COVIDSafeRegistrationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: COVIDSafeRegistrationFunctionRole
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        - PolicyName: AccessToDynamoDbRegistrationsTable
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: !GetAtt
                  - COVIDSafeRegistrationsTable
                  - Arn
      Path: /
  COVIDSafeFormRenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt
        - COVIDSafeFormRenderFunctionRole
        - Arn
      CodeUri: ./src/COVIDSafe/
      Handler: COVIDSafe::COVIDSafe.FormRenderFunction::FunctionHandler
      Runtime: dotnetcore3.1
      Events:
        LocationRequest:
          Type: Api
          Properties:
            Path: /location
            Method: get
  COVIDSafeRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt
        - COVIDSafeRegistrationFunctionRole
        - Arn
      CodeUri: ./src/COVIDSafe/
      Handler: COVIDSafe::COVIDSafe.RegisterFunction::FunctionHandler
      Runtime: dotnetcore3.1
      Events:
        RegisterRequest:
          Type: Api
          Properties:
            Path: /register
            Method: post
  COVIDSafeQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt
        - COVIDSafeRegistrationFunctionRole
        - Arn
      CodeUri: ./src/COVIDSafe/
      Handler: COVIDSafe::COVIDSafe.QueryFunction::FunctionHandler
      Runtime: dotnetcore3.1
      Events:
        RegisterRequest:
          Type: Api
          Properties:
            Path: /query
            Method: get
Outputs:
  COVIDSafeApi:
    Description: "API Gateway endpoint URL for Prod stage for COVIDSafe function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/location/"
  COVIDSafeFunction:
    Description: "COVIDSafe Lambda Function ARN"
    Value: !GetAtt COVIDSafeFormRenderFunction.Arn
  COVIDSafeFunctionIamRole:
    Description: "Implicit IAM Role created for COVIDSafe function"
    Value: !GetAtt COVIDSafeFormRenderFunction.Arn
