AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for aws-lambda-demo

Globals:
  Function:
    Timeout: 10

Resources:
  COVIDSafeFormRenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/COVIDSafe/
      Handler: COVIDSafe::COVIDSafe.FormRenderFunction::FunctionHandler
      Runtime: dotnetcore3.1
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        LocationRequest:
          Type: Api
          Properties:
            Path: /location
            Method: get

Outputs:
  COVIDSafeApi:
    Description: "API Gateway endpoint URL for Prod stage for COVIDSafe function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/location/"
  COVIDSafeFunction:
    Description: "COVIDSafe Lambda Function ARN"
    Value: !GetAtt COVIDSafeFormRenderFunction.Arn
  COVIDSafeFunctionIamRole:
    Description: "Implicit IAM Role created for COVIDSafe function"
    Value: !GetAtt COVIDSafeFormRenderFunction.Arn
